### ISSUE TITLE
CSS not capitalized in the Drop Down menu or title

### ISSUE THREAD

**Issue by courtneymorgan** [learn-co-curriculum/styling-with-css-intro#2]
The title is listed as Css
![screen shot 2017-08-01 at 2 46 15 pm](https://user-images.githubusercontent.com/29407254/28841448-4da47408-76c8-11e7-81e6-5c1208516771.png)

![screen shot 2017-08-01 at 2 47 19 pm](https://user-images.githubusercontent.com/29407254/28841474-5da0fb60-76c8-11e7-8c76-74661d437123.png)

**Comment by gj** [comment]
Fixed; thanks @courtneymorgan !
